// This file was auto-generated by ML.NET Model Builder. 

using System;
using Fondo9Sa3adaML.Model;

namespace Fondo9Sa3adaML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                New_reviews = @"nous tions merveilleusement accueillis par fatima un tr bonne accueil est la signature sofitel jardins des roses la qualit de la literie typique sofitel ce qui nou garantie une bonne nuit merci pour tout",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");
            Console.WriteLine($"New_reviews: {sampleData.New_reviews}");
            Console.WriteLine($"\n\nPredicted Rating value {predictionResult.Prediction} \nPredicted Rating scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
