// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Fondo9Sa3adaML.Model
{
    public class ModelInput
    {
        [ColumnName("rating"), LoadColumn(0)]
        public string Rating { get; set; }


        [ColumnName("new_reviews"), LoadColumn(1)]
        public string New_reviews { get; set; }


    }
}
